# Generated by Django 4.2.5 on 2023-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('submit_time', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
            ],
        ),
    ]
